# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/binah/StudyFiles/GradeTwo/Spring/图形学/HW_2/PM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/binah/StudyFiles/GradeTwo/Spring/图形学/HW_2/PM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/binah/StudyFiles/GradeTwo/Spring/图形学/HW_2/PM/CMakeFiles /Users/binah/StudyFiles/GradeTwo/Spring/图形学/HW_2/PM/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/binah/StudyFiles/GradeTwo/Spring/图形学/HW_2/PM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PM

# Build rule for target.
PM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PM
.PHONY : PM

# fast build rule for target.
PM/fast:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/build
.PHONY : PM/fast

basic.o: basic.cpp.o

.PHONY : basic.o

# target to build an object file
basic.cpp.o:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/basic.cpp.o
.PHONY : basic.cpp.o

basic.i: basic.cpp.i

.PHONY : basic.i

# target to preprocess a source file
basic.cpp.i:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/basic.cpp.i
.PHONY : basic.cpp.i

basic.s: basic.cpp.s

.PHONY : basic.s

# target to generate assembly for a file
basic.cpp.s:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/basic.cpp.s
.PHONY : basic.cpp.s

bezier.o: bezier.cpp.o

.PHONY : bezier.o

# target to build an object file
bezier.cpp.o:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/bezier.cpp.o
.PHONY : bezier.cpp.o

bezier.i: bezier.cpp.i

.PHONY : bezier.i

# target to preprocess a source file
bezier.cpp.i:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/bezier.cpp.i
.PHONY : bezier.cpp.i

bezier.s: bezier.cpp.s

.PHONY : bezier.s

# target to generate assembly for a file
bezier.cpp.s:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/bezier.cpp.s
.PHONY : bezier.cpp.s

bmp.o: bmp.cpp.o

.PHONY : bmp.o

# target to build an object file
bmp.cpp.o:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/bmp.cpp.o
.PHONY : bmp.cpp.o

bmp.i: bmp.cpp.i

.PHONY : bmp.i

# target to preprocess a source file
bmp.cpp.i:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/bmp.cpp.i
.PHONY : bmp.cpp.i

bmp.s: bmp.cpp.s

.PHONY : bmp.s

# target to generate assembly for a file
bmp.cpp.s:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/bmp.cpp.s
.PHONY : bmp.cpp.s

camera.o: camera.cpp.o

.PHONY : camera.o

# target to build an object file
camera.cpp.o:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/camera.cpp.o
.PHONY : camera.cpp.o

camera.i: camera.cpp.i

.PHONY : camera.i

# target to preprocess a source file
camera.cpp.i:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/camera.cpp.i
.PHONY : camera.cpp.i

camera.s: camera.cpp.s

.PHONY : camera.s

# target to generate assembly for a file
camera.cpp.s:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/camera.cpp.s
.PHONY : camera.cpp.s

color.o: color.cpp.o

.PHONY : color.o

# target to build an object file
color.cpp.o:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/color.cpp.o
.PHONY : color.cpp.o

color.i: color.cpp.i

.PHONY : color.i

# target to preprocess a source file
color.cpp.i:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/color.cpp.i
.PHONY : color.cpp.i

color.s: color.cpp.s

.PHONY : color.s

# target to generate assembly for a file
color.cpp.s:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/color.cpp.s
.PHONY : color.cpp.s

kit.o: kit.cpp.o

.PHONY : kit.o

# target to build an object file
kit.cpp.o:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/kit.cpp.o
.PHONY : kit.cpp.o

kit.i: kit.cpp.i

.PHONY : kit.i

# target to preprocess a source file
kit.cpp.i:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/kit.cpp.i
.PHONY : kit.cpp.i

kit.s: kit.cpp.s

.PHONY : kit.s

# target to generate assembly for a file
kit.cpp.s:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/kit.cpp.s
.PHONY : kit.cpp.s

light.o: light.cpp.o

.PHONY : light.o

# target to build an object file
light.cpp.o:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/light.cpp.o
.PHONY : light.cpp.o

light.i: light.cpp.i

.PHONY : light.i

# target to preprocess a source file
light.cpp.i:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/light.cpp.i
.PHONY : light.cpp.i

light.s: light.cpp.s

.PHONY : light.s

# target to generate assembly for a file
light.cpp.s:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/light.cpp.s
.PHONY : light.cpp.s

lodepng.o: lodepng.cpp.o

.PHONY : lodepng.o

# target to build an object file
lodepng.cpp.o:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/lodepng.cpp.o
.PHONY : lodepng.cpp.o

lodepng.i: lodepng.cpp.i

.PHONY : lodepng.i

# target to preprocess a source file
lodepng.cpp.i:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/lodepng.cpp.i
.PHONY : lodepng.cpp.i

lodepng.s: lodepng.cpp.s

.PHONY : lodepng.s

# target to generate assembly for a file
lodepng.cpp.s:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/lodepng.cpp.s
.PHONY : lodepng.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/main.cpp.s
.PHONY : main.cpp.s

material.o: material.cpp.o

.PHONY : material.o

# target to build an object file
material.cpp.o:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/material.cpp.o
.PHONY : material.cpp.o

material.i: material.cpp.i

.PHONY : material.i

# target to preprocess a source file
material.cpp.i:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/material.cpp.i
.PHONY : material.cpp.i

material.s: material.cpp.s

.PHONY : material.s

# target to generate assembly for a file
material.cpp.s:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/material.cpp.s
.PHONY : material.cpp.s

object.o: object.cpp.o

.PHONY : object.o

# target to build an object file
object.cpp.o:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/object.cpp.o
.PHONY : object.cpp.o

object.i: object.cpp.i

.PHONY : object.i

# target to preprocess a source file
object.cpp.i:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/object.cpp.i
.PHONY : object.cpp.i

object.s: object.cpp.s

.PHONY : object.s

# target to generate assembly for a file
object.cpp.s:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/object.cpp.s
.PHONY : object.cpp.s

photonmap.o: photonmap.cpp.o

.PHONY : photonmap.o

# target to build an object file
photonmap.cpp.o:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/photonmap.cpp.o
.PHONY : photonmap.cpp.o

photonmap.i: photonmap.cpp.i

.PHONY : photonmap.i

# target to preprocess a source file
photonmap.cpp.i:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/photonmap.cpp.i
.PHONY : photonmap.cpp.i

photonmap.s: photonmap.cpp.s

.PHONY : photonmap.s

# target to generate assembly for a file
photonmap.cpp.s:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/photonmap.cpp.s
.PHONY : photonmap.cpp.s

raytracer.o: raytracer.cpp.o

.PHONY : raytracer.o

# target to build an object file
raytracer.cpp.o:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/raytracer.cpp.o
.PHONY : raytracer.cpp.o

raytracer.i: raytracer.cpp.i

.PHONY : raytracer.i

# target to preprocess a source file
raytracer.cpp.i:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/raytracer.cpp.i
.PHONY : raytracer.cpp.i

raytracer.s: raytracer.cpp.s

.PHONY : raytracer.s

# target to generate assembly for a file
raytracer.cpp.s:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/raytracer.cpp.s
.PHONY : raytracer.cpp.s

scene.o: scene.cpp.o

.PHONY : scene.o

# target to build an object file
scene.cpp.o:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/scene.cpp.o
.PHONY : scene.cpp.o

scene.i: scene.cpp.i

.PHONY : scene.i

# target to preprocess a source file
scene.cpp.i:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/scene.cpp.i
.PHONY : scene.cpp.i

scene.s: scene.cpp.s

.PHONY : scene.s

# target to generate assembly for a file
scene.cpp.s:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/scene.cpp.s
.PHONY : scene.cpp.s

texture.o: texture.cpp.o

.PHONY : texture.o

# target to build an object file
texture.cpp.o:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/texture.cpp.o
.PHONY : texture.cpp.o

texture.i: texture.cpp.i

.PHONY : texture.i

# target to preprocess a source file
texture.cpp.i:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/texture.cpp.i
.PHONY : texture.cpp.i

texture.s: texture.cpp.s

.PHONY : texture.s

# target to generate assembly for a file
texture.cpp.s:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/texture.cpp.s
.PHONY : texture.cpp.s

vector3.o: vector3.cpp.o

.PHONY : vector3.o

# target to build an object file
vector3.cpp.o:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/vector3.cpp.o
.PHONY : vector3.cpp.o

vector3.i: vector3.cpp.i

.PHONY : vector3.i

# target to preprocess a source file
vector3.cpp.i:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/vector3.cpp.i
.PHONY : vector3.cpp.i

vector3.s: vector3.cpp.s

.PHONY : vector3.s

# target to generate assembly for a file
vector3.cpp.s:
	$(MAKE) -f CMakeFiles/PM.dir/build.make CMakeFiles/PM.dir/vector3.cpp.s
.PHONY : vector3.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... PM"
	@echo "... basic.o"
	@echo "... basic.i"
	@echo "... basic.s"
	@echo "... bezier.o"
	@echo "... bezier.i"
	@echo "... bezier.s"
	@echo "... bmp.o"
	@echo "... bmp.i"
	@echo "... bmp.s"
	@echo "... camera.o"
	@echo "... camera.i"
	@echo "... camera.s"
	@echo "... color.o"
	@echo "... color.i"
	@echo "... color.s"
	@echo "... kit.o"
	@echo "... kit.i"
	@echo "... kit.s"
	@echo "... light.o"
	@echo "... light.i"
	@echo "... light.s"
	@echo "... lodepng.o"
	@echo "... lodepng.i"
	@echo "... lodepng.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... material.o"
	@echo "... material.i"
	@echo "... material.s"
	@echo "... object.o"
	@echo "... object.i"
	@echo "... object.s"
	@echo "... photonmap.o"
	@echo "... photonmap.i"
	@echo "... photonmap.s"
	@echo "... raytracer.o"
	@echo "... raytracer.i"
	@echo "... raytracer.s"
	@echo "... scene.o"
	@echo "... scene.i"
	@echo "... scene.s"
	@echo "... texture.o"
	@echo "... texture.i"
	@echo "... texture.s"
	@echo "... vector3.o"
	@echo "... vector3.i"
	@echo "... vector3.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

